// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOxamyWq6AE9qes4weY_abBv4MCL7FXso',
    appId: '1:178269272264:web:0663a9bd88046ee452cdfd',
    messagingSenderId: '178269272264',
    projectId: 'mygenie-15512',
    authDomain: 'mygenie-15512.firebaseapp.com',
    storageBucket: 'mygenie-15512.appspot.com',
    measurementId: 'G-1F69KD2G16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBioKLRS0znZkVYcRkwsiecWh4H2FPxNNU',
    appId: '1:178269272264:android:7e513d0b2a846a1a52cdfd',
    messagingSenderId: '178269272264',
    projectId: 'mygenie-15512',
    storageBucket: 'mygenie-15512.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhR7IIviEbwdvfiLRJfi9qcxoqTwXNEqo',
    appId: '1:178269272264:ios:71c0c908d48ddb8552cdfd',
    messagingSenderId: '178269272264',
    projectId: 'mygenie-15512',
    storageBucket: 'mygenie-15512.appspot.com',
    iosClientId: '178269272264-bf59b6ju41p45a0uk9vkps1a3uj1oh71.apps.googleusercontent.com',
    iosBundleId: 'com.example.aboApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhR7IIviEbwdvfiLRJfi9qcxoqTwXNEqo',
    appId: '1:178269272264:ios:71c0c908d48ddb8552cdfd',
    messagingSenderId: '178269272264',
    projectId: 'mygenie-15512',
    storageBucket: 'mygenie-15512.appspot.com',
    iosClientId: '178269272264-bf59b6ju41p45a0uk9vkps1a3uj1oh71.apps.googleusercontent.com',
    iosBundleId: 'com.example.aboApp',
  );
}
